### PR TITLE
feat: add checkly source [sc-00]

### PR DESCRIPTION
**Pull request by ndom91**
## Affected Components
* [ ] Resources
* [ ] Tests
* [ ] Docs
* [x] Other

## Style
* [ ] Terraform code is formatted with `terraform fmt`
* [ ] Go code is formatted with `go fmt`

## Notes for the Reviewer

Added `SetChecklySource("TF")` from `checkly-go-sdk`.

Depends on: https://github.com/checkly/checkly-go-sdk/pull/65

### CODE REVIEW

**Comment by umutuzgur** [comment]
@ndom91 you need to update the go sdk version first

**Comment by ndom91** [comment]
@umutuzgur yeah I figure we'd have to merge that other PR first

**Review by umutuzgur — APPROVED** [review]
LGTM

**Comment by ianaya89** [comment]
Resolves https://github.com/checkly/terraform-provider-checkly/projects/1

**Pull request merged**
